version: '2'
services:
  judge:
    restart: always
    build: ./CodeJudge
    expose:
      - "8000"
    volumes:
      - ./CodeJudge:/usr/src/app/CodeJudge
    env_file: .env
    depends_on:
      - redis
      - postgres
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web:/usr/src/app/web
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    depends_on:
      - judge
      - postgres

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/app/static:/www/static
    depends_on:
      - web

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    env_file: .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:latest
    volumes_from:
      - data
    env_file: .env
    ports:
      - "6379:6379"
    expose:
      - "6379"
